name: NASA Project CI
on:
  # ketika push ke master atau pr maka akan menjalankan CI ini
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    runs-on: ubuntu-latest
    # This is where we define the different actions
    # that are going to be taken
    steps:
      # liat aja di docs nya
      - uses: actions/checkout@v3
      # We can name the step
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run build --prefix client
