name: NASA Project CI
on:
  # ketika push ke master atau pr maka akan menjalankan CI ini
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    # This is where we define the different actions
    # that are going to be taken
    steps:
      # liat aja di docs nya
      - uses: actions/checkout@v3
      # We can name the step
      - name: Use Node.js version 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build --prefix client
